spring:
#  mvc:
#    static-path-pattern: /static/**
  application:
    name: mips246
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ryan1?serverTimezone=UTC
    username: root
    password: '0623'
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
server:
  port: 8080
mybatis-plus:
  #  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.tongji.pojo
  global-config:
    id-type: 1
    db-column-underline: false
    refresh-mapper: true
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: true
      lazyLoadingEnabled: true
      multipleResultSetsEnabled: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
